on:
  pull_request:
    types: [opened]
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/clover.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 75
